@set allusersprofile=c:\programdata
@set appdata=c:\users\krey\appdata\roaming
@set carbon_mem_disable=1
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-of4vb5s
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=d:\ide\microsoft visual studio\2017\community\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set homedrive=c:
@set homepath=\users\krey
@set htmlhelpdir=c:\program files (x86)\html help workshop
@set include=d:\ide\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\include;d:\ide\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.14393.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.14393.0\shared;c:\program files (x86)\windows kits\10\include\10.0.14393.0\um;c:\program files (x86)\windows kits\10\include\10.0.14393.0\winrt
@set lib=d:\ide\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\lib\x86;d:\ide\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\lib\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\10\lib\10.0.14393.0\ucrt\x86;c:\program files (x86)\windows kits\10\lib\10.0.14393.0\um\x86
@set libpath=d:\ide\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\atlmfc\lib\x86;d:\ide\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\lib\x86;c:\program files (x86)\windows kits\10\unionmetadata;c:\program files (x86)\windows kits\10\references;c:\windows\microsoft.net\framework\v4.0.30319
@set localappdata=c:\users\krey\appdata\local
@set logonserver=\\desktop-of4vb5s
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=d:\ide\microsoft visual studio\2017\community\msbuild\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=4
@set onedrive=e:\onedrive
@set os=windows_nt
@set path=d:\ide\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\bin\hostx86\x86;d:\ide\microsoft visual studio\2017\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft sdks\typescript\2.2;d:\ide\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\testwindow;d:\ide\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;d:\ide\microsoft visual studio\2017\community\msbuild\15.0\bin\roslyn;d:\ide\microsoft visual studio\2017\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\html help workshop;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\windows kits\10\bin\10.0.14393.0\x86;d:\ide\microsoft visual studio\2017\community\\msbuild\15.0\bin;c:\windows\microsoft.net\framework\v4.0.30319;d:\ide\microsoft visual studio\2017\community\common7\ide\;d:\ide\microsoft visual studio\2017\community\common7\tools\;e:\ide\python27\;e:\ide\python27\scripts;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files (x86)\microsoft sdks\typescript\1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\dotnet\;c:\program files (x86)\skype\phone\;e:\ide\mingw\bin;e:\ide\python27\;e:\ide\msys64\usr\bin\;c:\users\krey\appdata\local\microsoft\windowsapps;c:\program files (x86)\java\jdk1.8.0_121\bin
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\krey\appdata\local\microsoft\visualstudio\15.0_8becb186\devenv.exe.config
@set platform=x86
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 42 stepping 7, genuineintel
@set processor_level=6
@set processor_revision=2a07
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=d:\ide\microsoft visual studio\2017\community\msbuild
@set pvs_vsinstalldir=d:\ide\microsoft visual studio\2017\community
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\krey\appdata\local\temp
@set tmp=c:\users\krey\appdata\local\temp
@set ucrtversion=10.0.14393.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-of4vb5s
@set userdomain_roamingprofile=desktop-of4vb5s
@set username=krey
@set userprofile=c:\users\krey
@set vbox_msi_install_path=e:\_tools\_pctools\virtualbox\
@set vcideinstalldir=d:\ide\microsoft visual studio\2017\community\common7\ide\vc\
@set vcinstalldir=d:\ide\microsoft visual studio\2017\community\vc\
@set vctoolsinstalldir=d:\ide\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\
@set vctoolsredistdir=d:\ide\microsoft visual studio\2017\community\vc\redist\msvc\14.10.25017\
@set visualstudiodir=e:\my documents\visual studio 2017
@set visualstudioedition=microsoft visual studio community 2017
@set visualstudioversion=15.0
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs120comntools=e:\ide\microsoft visual studio 12.0\common7\tools\
@set vs150comntools=d:\ide\microsoft visual studio\2017\community\common7\tools\
@set vsappiddir=d:\ide\microsoft visual studio\2017\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x86
@set vscmd_arg_tgt_arch=x86
@set vscmd_ver=15.0.26430.12
@set vsinstalldir=d:\ide\microsoft visual studio\2017\community\
@set vslang=1033
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata;c:\program files (x86)\windows kits\10\references
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.14393.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.14393.0\
@set windowssdkversion=10.0.14393.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set __dotnet_add_32bit=1
@set __dotnet_preferred_bitness=32
@set __vscmd_preinit_path=e:\ide\python27\;e:\ide\python27\scripts;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files (x86)\microsoft sdks\typescript\1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files\dotnet\;c:\program files (x86)\skype\phone\;e:\ide\mingw\bin;e:\ide\python27\;e:\ide\msys64\usr\bin\;c:\users\krey\appdata\local\microsoft\windowsapps;c:\program files (x86)\java\jdk1.8.0_121\bin

@call "C:\Program Files (x86)\PVS-Studio\x86\clang.exe" --driver-mode=cl @"C:\Users\krey\Source\Repos\battlecats\RoomDesigner\BattleCats\BattleCatsView.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1